#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=95

USE_PROCD=1

PROCD_DEBUG=1

start_service() {
    procd_open_instance
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-300} ${respawn_retry:-5}
    procd_set_param command /data/bin/WTP /data/config/capwap/
    procd_set_param stdout 1
    procd_set_param stderr 1
    #procd_set_param limits ar="unlimited"
    procd_set_param limits core="unlimited"
    #procd_set_param limits cpu="unlimited"
    #procd_set_param fsize data="unlimited"
    #procd_set_param limits fsize="unlimited"
    procd_set_param limits memlock="unlimited"
    #procd_set_param limits nofile="unlimited"
    procd_set_param limits nproc="unlimited"
    #procd_set_param limits sigpending="unlimited"
    procd_close_instance
}

stop_service() {
	echo "stop_service CAPWAP WTP"
	kill -9 `pgrep WTP`
}
